apiVersion: v1
kind: Pod
metadata:
  name: deploy-service-pod
  labels:
    job: deploy-service
spec:
  containers:
    - name: git
      image: alpine/git
      command: ["cat"]
      tty: true
    - name: helm-cli
      image: lachlanevenson/k8s-helm
      command: ["cat"]
      tty: true